apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/erictita/gitops-demo.git
    targetRevision: main
    path: helm/express-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true