replicaCount: 2

image:
  repository: admintita/express-app
  tag: ""   # CI/CD will inject git SHA or version

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

ingress:
  enabled: true
  className: nginx
  host: express-app.local
  path: /
  pathType: Prefix