apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: admintita/express-app:f9198d70e630cdf769701a4711c059ebc5cfb9f5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000