apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: admintita/express-app:7ea13c3db424b726b2f3549f13e26a1f3dbb372d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000